name: Publish

'on':
    push:
        tags:
            - "*.*.*-*"

env:
    DOCKER_IMAGE: etriasnl/percona-toolkit

jobs:
    image:
        uses: etrias-nl/workflows/.github/workflows/docker-publish.yaml@main
        with:
            image: ${{ env.DOCKER_IMAGE }}
